"""empty message

Revision ID: 2d03479be132
Revises: 2c618f821064
Create Date: 2023-07-07 15:43:15.269703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d03479be132'
down_revision = '2c618f821064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
